Datetime:2024-09-19 22:10:40,263 - Level:INFO - Module:exchanges_update - Function:exchanges_update - Message:Exchanges checked, no new exchanges detected
Datetime:2024-09-19 22:12:04,388 - Level:INFO - Module:ticker_update - Function:ticker_update - Message:Exchanges checked, 182276 tickers added to seldon_db
Datetime:2024-09-19 22:12:15,968 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'
Datetime:2024-09-19 22:12:18,909 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'ESINMU' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'ESINMU' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'ESINMU' for key 'PRIMARY'
Datetime:2024-09-19 22:12:30,072 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'INF109K012M7NSE' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'INF109K012M7NSE' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'INF109K012M7NSE' for key 'PRIMARY'
Datetime:2024-09-19 22:12:38,409 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'REBLXHEL' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'REBLXHEL' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'REBLXHEL' for key 'PRIMARY'
Datetime:2024-09-19 22:13:00,878 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'AAANYSE ARCA' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'AAANYSE ARCA' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'AAANYSE ARCA' for key 'PRIMARY'
Datetime:2024-09-19 22:13:10,944 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'TRAD-TRXSTO' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'TRAD-TRXSTO' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'TRAD-TRXSTO' for key 'PRIMARY'
Datetime:2024-09-19 22:13:25,080 - Level:INFO - Module:ticker_update - Function:ticker_update - Message:Exchanges checked, 2578 tickers added to seldon_db
Datetime:2024-09-19 22:13:35,226 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'
