Datetime:2024-09-18 22:20:09,771 - Level:INFO - Module:exchanges_update - Function:exchanges_update - Message:Exchanges checked, 77 exchanges added to seldon_db
Datetime:2024-09-18 22:21:37,866 - Level:INFO - Module:ticker_update - Function:ticker_update - Message:Exchanges checked, 182290 tickers added to seldon_db
Datetime:2024-09-18 22:22:58,437 - Level:INFO - Module:exchanges_update - Function:exchanges_update - Message:Exchanges checked, no new exchanges detected
Datetime:2024-09-18 22:23:09,077 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'
Datetime:2024-09-18 22:23:12,020 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'ESINMU' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'ESINMU' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'ESINMU' for key 'PRIMARY'
Datetime:2024-09-18 22:23:23,956 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'INF109K012M7NSE' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'INF109K012M7NSE' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'INF109K012M7NSE' for key 'PRIMARY'
Datetime:2024-09-18 22:23:30,532 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'REBLXHEL' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'REBLXHEL' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'REBLXHEL' for key 'PRIMARY'
Datetime:2024-09-18 22:24:12,015 - Level:INFO - Module:exchanges_update - Function:exchanges_update - Message:Exchanges checked, no new exchanges detected
Datetime:2024-09-18 22:24:23,326 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'BAIEMMAAXCSE' for key 'PRIMARY'
Datetime:2024-09-18 22:24:26,082 - Level:ERROR - Module:seldon_db_toolkit - Function:execute_query - Message:1062 (23000): Duplicate entry 'ESINMU' for key 'PRIMARY'
Traceback (most recent call last):
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate entry 'ESINMU' for key 'PRIMARY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/seldon_project/lib/toolkit/seldon_db_toolkit.py", line 31, in execute_query
    cursor.execute(query)
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/.pyenv/versions/3.12.5/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'ESINMU' for key 'PRIMARY'
